"""empty message

Revision ID: ba33fbd7632e
Revises: 
Create Date: 2025-04-03 19:15:12.402260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba33fbd7632e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('conversation_record')
    op.drop_table('student')
    op.drop_table('conversation_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_detail',
    sa.Column('detail_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('conversation_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', mysql.TEXT(), nullable=False),
    sa.Column('student_answer', mysql.TEXT(), nullable=True),
    sa.Column('reference_answer', mysql.TEXT(), nullable=True),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['conversation_record.record_id'], name='conversation_detail_ibfk_1'),
    sa.PrimaryKeyConstraint('detail_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conversation_record',
    sa.Column('record_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('course_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('conversation_time', mysql.DATETIME(), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('average_score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('analysis_report', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='conversation_record_ibfk_2'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name='conversation_record_ibfk_1'),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('course_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('course_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
